server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**
            - id: RATING-SERVICE
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/ratings/**
  config:
    import: optional:configserver:http://localhost:8085

#okta configuration for API Gateway
okta:
  oauth2:
    issuer: https://integrator-2489353.okta.com/oauth2/default
    audience: api://default
    client-id: 0oav7eg3p35EWHU3v697
    client-secret: TZ5T8OJCTzoFIRcFrDfCtbmmeV2DNCj6TK3vcGlIl-bjctTH8Pn_MccbIwiNnE92
    scopes: openid , profile, email , offline_access

